### ISSUE TITLE
Think about adding a README? 

### ISSUE THREAD

**Issue by tmcelroy2202** [greysin44543/Gavin-Gamin-notes#2]
Readme files show up whenever someone opens the repository. It is what you look at when you first open a repository. adding one will help if you want to share this repository ever directly as a link to the github. It doesn't have to be built out. I make mine just an explanation of how im writing the notes and how to best read them. All you have to do is make a file named README.md and the stuff will show up in the repository when you open the repository.

mark this issue as completed if you do, or as wont fix if you dont want to.

**Comment by greysin44543** [comment]
Done 👍
